# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3f4c8edd8ca0d0d905476aeece83dc6efc6bad50b9a89c0dbb262ec48cf75847e9b54d15fd421342b7c1a9968b5582a23414fed450f0d41f7620a830961795

test:
  secret_key_base: f750bbeec88bfd76650a4d088fb656af034f6d3738d8bdbc0f8a6838bae0f20966f1a5efd65f890c92c2b1a4c4e5edb6b610d27a854d4f399327bc3761f6c3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
